language: cpp

sudo: false

compiler:
  - gcc
  - clang


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      #- kubuntu-backports # cmake 2.8.12
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - cmake
      - cmake-data
   
before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq
#  - sudo apt-get install -y -qq gcc-4.8 g++-4.8
#currently disabled 4.8 gcc test but use it for clang
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - cd lib
  - tar xjf boost_1_55_0.tar.bz2
  - cd ../pol-core/bin-build
  - chmod a+x build_linux.sh

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - ./build_linux.sh

#  - cd ../testsuite/escript
#  - /usr/bin/python performtests.py -c ../../pol-core/bin/ecompile-dynamic -r ../../pol-core/bin/runecl-dynamic

