language: cpp
compiler:
  - gcc
script: 
  - cd pol-core && chmod a+x buildcore && ./buildcore
  - cd ../testsuite/escript && /usr/bin/python performtests.py -c ../../pol-core/bin/ecompile-dynamic -r ../../pol-core/bin/runecl-dynamic
