language: cpp

sudo: false

compiler:
  - gcc
  - clang


addons:
  apt:
    #ref: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports # cmake 3.2.3
    #ref: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - cmake
      - cmake-data
   
before_install:
  - cd lib
  - tar xjf boost_1_55_0.tar.bz2
  - cd ../pol-core/bin-build
  - chmod a+x build_linux.sh

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - ./build_linux.sh

#  - cd ../testsuite/escript
#  - /usr/bin/python performtests.py -c ../../pol-core/bin/ecompile-dynamic -r ../../pol-core/bin/runecl-dynamic

