version: 100.{build} 
clone_depth: 1 
clone_folder: c:\projects\pol_testing
cache:
- lib/curl-7.57.0
image: Visual Studio 2017
platform: x64
configuration: Release

build:
#  parallel: true
#  project: bin-build/polserver.sln
  verbosity: minimal

init:
  - git config --global core.autocrlf true

install:
  - cd bin-build
    #  - cmake .. -G "Visual Studio 15 2017 Win64"
  - call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
  - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
build_script:
  - cmake --build . --config Release -- -j 2

test_script:
    #- c:\\Python34\\python.exe performtests.py ..\\..\\bin\\Release\\ecompile.exe ..\\..\\bin\\Release\\runecl.exe -n 5 -q
    #- c:\\Python34\\python.exe performtests.py ..\\..\\bin\\ecompile.exe ..\\..\\bin\\runecl.exe -n 5 -q
  - ctest -T Test -j 2 --output-on-failure --repeat-until-fail 5
  - cd ..\\testsuite\\escript
  - cd ..\\style
  - c:\\Python34\\python.exe checknl.py -q

after_test:
  - cd ..\\..\\bin-build
  - cmake --build . --config Release --target package
  - ps: >-
      Get-ChildItem ..\\bin\\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      Invoke-WebRequest -Uri https://github.com/kovbal/appveyor-ctest-uploader/archive/v1.0.0.zip -OutFile ctest-uploader.zip
      Expand-Archive -Path .\ctest-uploader.zip -DestinationPath .\
      mv .\appveyor-ctest-uploader-* appveyor-ctest-uploader
      . .\appveyor-ctest-uploader\upload-ctest-report.ps1
      foreach($f in $(ls Testing\*\Test.xml))
      { upload-ctest-report $f }


deploy: off

notifications:
- provider: Email
  to:
    - polteam@polserver.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
